# Generated by Django 5.2.1 on 2025-06-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Gallary',
        ),
    ]
